package com.example.compose.previewscreenshot

import android.content.res.Configuration
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.ui.text.withStyle
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.SpanStyle
import androidx.compose.ui.text.buildAnnotatedString
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.tooling.preview.Preview
import com.example.compose.previewscreenshot.ui.theme.SampleTheme
import org.jsoup.Jsoup
import org.jsoup.nodes.Element
import org.jsoup.nodes.TextNode
import org.mozilla.javascript.Context
import org.mozilla.javascript.Scriptable
import org.mozilla.javascript.ScriptableObject

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContent {
            SampleTheme {
                Scaffold(modifier = Modifier.fillMaxSize()) { innerPadding ->
                    GreetingPage(modifier = Modifier.padding(innerPadding))
                }
            }
        }
    }
}

@Composable
fun GreetingPage(modifier: Modifier = Modifier) {
    Surface(modifier = modifier.fillMaxSize()) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            Text(
                text = "¡Hola!",
                fontSize = 32.sp,
                fontWeight = FontWeight.Bold
            )

            Text(
                text = "Welcome to our Compose Screenshot Testing demo!",
                fontSize = 20.sp
            )

            Button(
                onClick = { /* Do something */ },
                shape = RoundedCornerShape(8.dp),
                modifier = Modifier.align(Alignment.CenterHorizontally)
            ) {
                Text(text = "Click Me")
            }

            Text(
                text = "Here is a list of features:",
                fontSize = 18.sp,
                fontWeight = FontWeight.SemiBold
            )

            Column(
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                Text(text = "• Compose UI support")
                Text(text = "• Locale-specific screenshots")
                Text(text = "• Light and Dark mode testing")
                Text(text = "• Screenshot validation workflow")
            }

            Spacer(modifier = Modifier.height(16.dp))

            Text(
                text = "Below is static HTML-rendered content:",
                fontSize = 18.sp,
                fontWeight = FontWeight.SemiBold
            )

            HtmlText(
                html = """
                    <h1 style="color:red;">Hello from WebView!</h1>
                    <p>This HTML content is now rendered natively in Compose and will appear in CI screenshots.</p>
                """.trimIndent()
            )

            Spacer(modifier = Modifier.height(24.dp))

            Text(
                text = "Below is JS-generated content (via Rhino):",
                fontSize = 18.sp,
                fontWeight = FontWeight.SemiBold
            )

            JsDocumentWriteContent(
                jsCode = """
                    document.write('<h1 style="color:blue;">Hello from Rhino!</h1>');
                    document.write('<p>This content was generated by JavaScript run inside Rhino engine.</p>');
                """.trimIndent()
            )
        }
    }
}

@Composable
fun HtmlText(html: String) {
    val annotatedString = remember(html) {
        parseHtmlToAnnotatedString(html)
    }
    Text(
        text = annotatedString,
        fontSize = 16.sp,
        textAlign = TextAlign.Start
    )
}

fun parseHtmlToAnnotatedString(html: String): AnnotatedString {
    val document = Jsoup.parse(html)
    val body = document.body()
    return buildAnnotatedString {
        parseElement(body)
    }
}

private fun AnnotatedString.Builder.parseElement(element: Element) {
    for (node in element.childNodes()) {
        when (node) {
            is TextNode -> {
                append(node.text())
            }
            is Element -> {
                val inlineColor = node.attr("style")
                    .substringAfter("color:", "")
                    .substringBefore(";")
                    .trim()

                val spanStyle = if (inlineColor.isNotEmpty()) {
                    SpanStyle(color = parseColor(inlineColor))
                } else {
                    SpanStyle()
                }

                when (node.tagName().lowercase()) {
                    "h1" -> withStyle(spanStyle.merge(SpanStyle(fontSize = 24.sp, fontWeight = FontWeight.Bold))) {
                        parseElement(node)
                    }
                    "p" -> withStyle(spanStyle) {
                        parseElement(node)
                        append("\n\n")
                    }
                    else -> withStyle(spanStyle) {
                        parseElement(node)
                    }
                }
            }
        }
    }
}

private fun parseColor(colorString: String): Color {
    return when (colorString.lowercase()) {
        "red" -> Color.Red
        "blue" -> Color.Blue
        "green" -> Color.Green
        "black" -> Color.Black
        else -> Color.Black // fallback default
    }
}

/**
 * A composable to run JS code that uses document.write and render the resulting HTML natively.
 */
@Composable
fun JsDocumentWriteContent(jsCode: String) {
    // Run the JS code inside Rhino, extract the concatenated document.write output.
    val htmlOutput = remember(jsCode) {
        runJsDocumentWrite(jsCode)
    }

    HtmlText(htmlOutput)
}

fun runJsDocumentWrite(jsCode: String): String {
    // We'll collect document.write calls here
    val outputBuilder = StringBuilder()

    val context = Context.enter()
    context.optimizationLevel = -1 // interpreted mode, safer on Android
    return try {
        val scope = context.initStandardObjects()

        // Define document object with write method in JS scope
        val document = object : ScriptableObject() {
            override fun getClassName() = "document"

            @Suppress("unused")
            fun write(text: String) {
                outputBuilder.append(text)
            }
        }
        ScriptableObject.putProperty(scope, "document", Context.javaToJS(document, scope))

        // Evaluate the JS code which calls document.write(...)
        context.evaluateString(scope, jsCode, "script", 1, null)

        outputBuilder.toString()
    } catch (e: Exception) {
        // In case JS throws, just return error message as HTML
        "<p style=\"color:red;\">JavaScript error: ${e.message}</p>"
    } finally {
        Context.exit()
    }
}

@Preview(showBackground = true)
@Preview(showBackground = true, locale = "es")
@Preview(showBackground = true, name = "Dark", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Composable
fun GreetingPreview() {
    SampleTheme {
        GreetingPage()
    }
}
