# Workflow name
name: Compose Preview Screenshot
on:
  # When it will be triggered
  # And in which branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Build project and run screenshot tests
        working-directory: ./ui/PreviewScreenshot
        run: |
         ./gradlew validateDebugScreenshotTest
         ls -R .

      - name: Upload Screenshot Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ./ui/PreviewScreenshot/build